# Generated by Django 5.2 on 2025-05-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customusermodel_groups_customusermodel_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
