# Generated by Django 5.2 on 2025-04-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='speed',
            field=models.IntegerField(default=60),
        ),
    ]
