# Generated by Django 5.2 on 2025-05-01 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vege', '0005_subject_marks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='SubjectMarks',
        ),
    ]
